Removed connected_plans from backend
habitat-sh/builder pull request #1833
Opened 2024-08-05 12:04 UTC by sougata-progress

story : CHEF-12418

2024-08-05 12:09 UTC, sougata-progress commented
hi @mwrock i have removed the logic for the functions i could find, which i think are related to connected plans. please let me know if there are any other functions that are related to this ex. create_job, etc, as i couldn't figure out if the other functions are needed or not. 
another thing, do i need to run make lint and fmt on this pr as well?

2024-08-07 07:11 UTC, agadgil-progress reviewed
In addition to the comments mentioned, you may want to look at the following files and possibly update/remove 

1. `test/builder-api/src/origin.js` - Fix 'project' related test cases. 
2. possibly comment out a few tests in `test/builder-api/project.js` or may be comment out this file in `test/builder-api/api.js` with a `//TODO` added 
3. Likely following functions in `app/actions/gitHub.ts` are not required as well - (because they were being used only in the `project.ts`) `*githubInstallations` and `*githubRepositories`. This might be a good time to remove those.

2024-08-08 21:41 UTC, mwrock commented on test/builder-api/src/origins.js
> -    it("succeeds", function (done) {
you want to keep this test. Otherwise the origin is not deleted and that would explain your test failure in the build.

2024-08-12 16:36 UTC, mwrock requested changes

2024-08-12 22:37 UTC, sougata-progress commented
hi @mwrock I have made the requested changes

2024-08-12 22:40 UTC, mwrock approved these changes

2024-08-13 07:43 UTC, merged